package: binstar

platform:
  - linux-64
  - osx-64
  - win-64

engine:
 - python=2.7
 - python=3.4

install:
  - conda install pip setuptools clyent coverage mock
  - python setup.py develop

test:
  - python binstar_client/tests/runtests.py

script:
  - conda build conda.recipe

build_targets: [conda]
