{% set data = load_setup_py_data() %}
package:
  name: anaconda-client
  version: {{ data.get('version') }}

source:
  git_url: ../

build:
  entry_points:
    - anaconda = binstar_client.scripts.cli:main
    - binstar = binstar_client.scripts.cli:main
    - conda-server = binstar_client.scripts.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - clyent >=1.2.0
    - conda-package-handling >=1.7.3
    - defusedxml >=0.7.1
    - nbformat >=4.4.0
    - python-dateutil >=2.6.1
    - pytz >=2021.3
    - pyyaml >=3.12
    - requests >=2.20.0
    - requests-toolbelt >=0.9.1
    - setuptools >=58.0.4
    - six >=1.15.0
    - tqdm >=4.56.0
    - urllib3 >=1.26.4,<2

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: BSD
  license_file: LICENSE.md
  summary: {{ data.get('description') }}
