{% set data = load_setuptools()%}
package:
  name: conda-server
  version: {{data.get('version')}}

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - clyent
    - requests
    - pyyaml
    - dateutil
    - pytz
    - pillow

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
